# Generated by Django 6.0.5 on 2026-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id_aplic', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_sit', models.IntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DateConductEvent',
            fields=[
                ('id_con_event', models.AutoField(primary_key=True, serialize=False)),
                ('date_con', models.DateTimeField()),
                ('max_member', models.IntegerField()),
            ],
            options={
                'db_table': 'Date_conduct_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'Event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id_pay', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pay_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
