# Generated by Django 6.0.5 on 2026-05-15 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revie',
            fields=[
                ('id_revie', models.IntegerField(primary_key=True, serialize=False)),
                ('review', models.TextField(blank=True, null=True)),
                ('id_aplic', models.ForeignKey(db_column='id_aplic', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.application')),
            ],
        ),
    ]
