# Generated by Django 6.0.5 on 2026-05-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_revie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revie',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='revie',
            table='review',
        ),
    ]
