# Generated by Django 6.0.5 on 2026-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_revie_options_alter_revie_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revie',
            name='id_revie',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
