# Generated by Django 6.0.5 on 2026-05-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_revie_id_revie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'managed': True},
        ),
    ]
